### ISSUE TITLE
[Feature Request] Please Update Mermaid to v11.1.0+ ！！！

### ISSUE THREAD

**Issue by Shapeno** [shd101wyy/crossnote#358]
**Why**
The latest mermaid supports Packet Diagram, which is very important for people working in networking and protocol. I really hope to add this feature to the project and update it synchronously to markdown-preview-enhanced. After the update, I will recommend markdown-preview-enhanced to my colleagues.

**Solution**
Update the dependencies\mermaid\mermaid.min.js to the latest. I've tried, now it's working well.

**Comment by shd101wyy** [comment]
Will do this weekend :+1:

**Comment by shd101wyy** [comment]
Done.
