### ISSUE TITLE
[Feature Request] loading more logos in mermaid for showing aws logos

### ISSUE THREAD

**Issue by Take-Me1010** [shd101wyy/crossnote#361]
**Is your feature request related to a problem? Please describe.**

Recent mermaid update provides architecture Diagrams and its version is supported in crossnote now. Thenk you for your quick update!
So I tried writing AWS architecture diagrams following [an official examle](https://mermaid.js.org/syntax/architecture.html#icons).
However, loading icons for aws services is required; I found loading icons is difficult in markdown preview enhanced extension (VSCode).
for examle, I tried adding codes in head.html as follows:
```html
<script>
window['mermaid'].registerIconPacks([
  {
    name: 'logos',
    loader: () =>
      fetch('https://unpkg.com/@iconify-json/logos/icons.json').then((res) => res.json()),
  },
]);
</script>
```

But nothing happend.

**Describe the solution you'd like**
Adding a few lines to register icons ([mermaid official code](https://mermaid.js.org/syntax/architecture.html#icons)) around [src/webview/containers/preview.ts#L498](https://github.com/shd101wyy/crossnote/blob/9708d58530d8049b09d990bda29fb727fd65de59/src/webview/containers/preview.ts#L498) as follows:

```javascript
mermaid.registerIconPacks([
  {
    name: 'logos',
    loader: () =>
      fetch('https://unpkg.com/@iconify-json/logos/icons.json').then((res) => res.json()),
  },
]);
```

I confirmed that inserting equivalent code in ~/.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.8.14\crossnote\webview directly make aws logos on the diagrams visible.

**Describe alternatives you've considered**
The solution above seems easy.
But I think more flexible option strategy for loading logos exists.
For examle, adding options for loading logos in config.js is considered:
```javascript:config.js
((() => {
  return {
    mermaidConfig: {
      "startOnLoad": false,
      "additionalLogos": [
        {name: "logos", loader: () => fetch('https://unpkg.com/@iconify-json/logos/icons.json').then((res) => res.json()), }
      ]
    },
  };
})())
```

**Additional context**
if adding loading logos for mermaid is implemented, it is very easy to write AWS architectures as follows:

```
architecture-beta
    service ec2(logos:aws-ec2)[EC2]
    service s3(logos:aws-s3)[S3]
    
    ec2:R -- L:s3
```

↓ rendered

![image](https://github.com/user-attachments/assets/8c1cec77-bbde-49ec-8b2c-80c18332a25e)

**Comment by shd101wyy** [comment]
Hi @Take-Me1010 , I just tried this and it worked. So you can run `Markdown Preview Enhanced: Customize Preview Html Head`, then add the following content to the `head.html`:

```html
<script type="text/javascript">
  const configureMermaidIconPacks = () => {
    window["mermaid"].registerIconPacks([
      {
        name: "logos",
        loader: () =>
          fetch("https://unpkg.com/@iconify-json/logos/icons.json").then(
            (res) => res.json()
          ),
      },
    ]);
  };

  document.addEventListener("DOMContentLoaded", function () {
    // your code here
    configureMermaidIconPacks();
  });
  configureMermaidIconPacks();
</script>
```

![image](https://github.com/user-attachments/assets/b205f93c-5b6c-46e0-b16b-b969c6936510)

It seems we have to call `configureMermaidIconPacks()` function twice to make it work.

**Comment by Take-Me1010** [comment]
Thanks for reply, @shd101wyy !
Oh, really? ... it works lol

it is curious that calling `configureMermaidIconPacks` twice works well.
So I tried searching the answer of this behavior.
I finally found the code below also works well!

```head.html
<script type="text/javascript">
   const configureMermaidIconPacks = () => {
    window["mermaid"].registerIconPacks([
      {
        name: "logos",
        loader: () =>
          fetch("https://unpkg.com/@iconify-json/logos/icons.json").then(
            (res) => res.json()
          ),
      },
    ]);
  };

  if (document.readyState !== 'loading') {
    configureMermaidIconPacks();
  } else {
    document.addEventListener("DOMContentLoaded", () => {
      configureMermaidIconPacks();
    });
  }
</script>
```

I think such interesting trick comes from this: https://stackoverflow.com/questions/39993676/code-inside-domcontentloaded-event-not-working ; hence my head.html code will be better :)
It would be nice if this example code is shown on the document.

**Comment by shd101wyy** [comment]
Please feel free to submit PR to this repository https://github.com/shd101wyy/markdown-preview-enhanced which contains the documentation for the website https://shd101wyy.github.io/markdown-preview-enhanced

Thank you!

**Comment by Take-Me1010** [comment]
Yeah I will make PR for it, thanks!
